# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and publish with Gradle
      run: ./gradlew clean build publish
    - name: Cache
      uses: actions/cache@v2.0.0
      with:
    # A list of files, directories, and wildcard patterns to cache and restore
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.gradle/wrapper
        key: forge_gradle
        restore-keys: |
           forge_gradle
           
          
          
